### ISSUE TITLE
setSignText Not Permanent?

### ISSUE THREAD

**Issue by zedman2000** [Connor4898/ModPE-Scripts#12]
Hello,
I'm not sure this is intentional or not, but I wanted to set some text, but have it be permanent.
As it is, it seems that any text that is set by script, is removed as soon as I exit the game...or it is not properly saved into the tileEntity Block that signs get.
That is, the script would say, set some coordinates of a different block on line 2.
Then, when you tap that sign, my script is supposed to read those coordinates out of line 2, which does all seem to work.  So, at least in some temporary way, the data is being placed into that "sign".  However, every time you quit the game, the data that was "in" the signs disappears.  The original text (if I had any) is placed back into the sign.

Is there some kind of trick to this?  I have tried to remove and create the item at the given coordinates, but do not see any way to write into the separate database that includes the text from the 4 lines.

**Comment by sliceofcode** [comment]
@zedman2000 Hmm, it seems as if this is a BlockLauncher problem. Have you tried contacting @zhuowei?

**Comment by zedman2000** [comment]
@sliceofcode yes, I was pointed there by MrARM.  I put in the same issue there.  Thanks for the tip.

BTW, I did find that if you place another sign next to the sign that Block Launcher set the text to, then quit the game and re-enter, it will save that sign.  This only seems to work for 1 sign at a time.  I've not tried a LOT of combinations of things yet...so, at this time, I would think this could be closed here as it does seem to be a Block Launcher issue.

**Comment by zedman2000** [comment]
@sliceofcode why did you close this?  It is still an issue in 0.12

**Comment by zedman2000** [comment]
oh, yeah, this is the ModPE issues...not the BL issues page.  Nevermind.
