### ISSUE TITLE
Level.addParticle

### ISSUE THREAD

**Issue by AndreyNazarchuk** [Connor4898/ModPE-Scripts#13]
In: https://github.com/Connor4898/ModPE-Scripts/wiki/ModPE-Scripts-Functions-List
It says that particleType is an int, while: https://github.com/Connor4898/ModPE-Scripts/wiki/Particle-types does not have any ints for particle types, only names?????
can I still use "heart" or what???? :)

**Comment by minecraftmuse3** [comment]
It's because each particle type (in your case, "heart") has a corresponding integer code

**Comment by AndreyNazarchuk** [comment]
What are the int codes?

**Comment by PEMapModder** [comment]
Wow this repo is still alive :interrobang:

**Comment by AndreyNazarchuk** [comment]
Found them, thanks!

**Comment by sliceofcode** [comment]
Resolved.
