### ISSUE TITLE
Commands running twice

### ISSUE THREAD

**Issue by scratchyone** [Connor4898/ModPE-Scripts#15]
When I run commands, they seem to run twice. When I run help, I get something like
```
Help page 2/5
commands...
Help page 2/5
commands...
```
Both are exactly the same. It seems to happen to all commands

**Comment by scratchyone** [comment]
I think it's more likely that it's only outputting twice, not running twice. Still an issue though.

**Comment by sliceofcode** [comment]
@scratchyone Can you please show us your cods?

**Comment by scratchyone** [comment]
My whats?

On Sat, May 7, 2016 at 12:40 PM, cheesy <notifications@github.com> wrote:

> @scratchyone <https://github.com/scratchyone> Can you please show us your
> cods?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Connor4898/ModPE-Scripts/issues/15#issuecomment-217650761>
>



--

**Comment by sliceofcode** [comment]
@scratchyone Sorry, your code.

**Comment by scratchyone** [comment]
Oops. Thanks. This is for singleplayercommands.

On Sat, May 7, 2016 at 2:34 PM, cheesy <notifications@github.com> wrote:

> @scratchyone <https://github.com/scratchyone> Sorry, your code.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Connor4898/ModPE-Scripts/issues/15#issuecomment-217660624>
>



--

**Comment by sliceofcode** [comment]
SPC isn't maintained anymore, so we recommend that you use another mod anyways.

**Comment by FLStudioKing420** [comment]
I

**Comment by FLStudioKing420** [comment]
I think its becuz ur using <strong>OLD VERSION</strong> of blocklauncher
